---
# samba4_ad_domaincontroller/tasks/configure_bind_dns_service.yml

- name: 'Install Bind packages'
  package:
    name: "{{ bind_packages }}"
    state: 'present'
  notify:
    - 'Stop Bind service if it has been started during installation'

- name: 'Add settings to /etc/bind/named.conf.options'
  template:
    src: 'Debian10/named.conf.options.j2'
    dest: '/etc/bind/named.conf.options'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Add include for /var/lib/samba/bind-dns/named.conf to /etc/bind/named.conf.local'
  lineinfile:
    path: '/etc/bind/named.conf.local'
    regex: 'include "/var/lib/samba/bind-dns/named.conf";'
    line: 'include "/var/lib/samba/bind-dns/named.conf";'
    create: 'true'
    owner: 'root'
    group: "{{ bind_group }}"
    mode: '0644'

#
# Fix directory permissions
#

- name: "Fix permissions on directory {{ item.path }}"
  file:
    path: "{{ item.path }}"
    state: 'directory'
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ bind_directories }}"

#
# Fix file permissions
#

# - name: "Fix permissions on file {{ item.path }}"
#   file:
#     path: "{{ item.path }}"
#     state: 'file'
#     owner: "{{ item.owner }}"
#     group: "{{ item.group }}"
#     mode: "{{ item.mode }}"
#   with_items: "{{ bind_files }}"
