---
# samba4_ad_domaincontroller/tasks/configure_bind_dns_service.yml

- name: 'Install Bind packages'
  package:
    name: "{{ bind_packages }}"
    state: 'present'
  notify:
    - 'Stop Bind service if it has been started during installation'

- name: 'Add settings to /etc/bind/named.conf.options'
  template:
    src: 'Debian10/named.conf.options.j2'
    dest: '/etc/bind/named.conf.options'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Add include for /var/lib/samba/bind-dns/named.conf to /etc/bind/named.conf.local'
  lineinfile:
    path: '/etc/bind/named.conf.local'
    regex: 'include "/var/lib/samba/bind-dns/named.conf";'
    line: 'include "/var/lib/samba/bind-dns/named.conf";'
    create: 'true'
    owner: 'root'
    group: "{{ bind_group }}"
    mode: '0644'

- name: 'Fix permissions on directory /var/lib/samba/bind-dns/'
  file:
    path: '/var/lib/samba/bind-dns/'
    state: 'directory'
    owner: 'root'
    group: "{{ bind_group }}"
    mode: '0750'

- name: 'Fix permissions on file /var/lib/samba/bind-dns/named.conf'
  file:
    path: '/var/lib/samba/bind-dns/named.conf'
    state: 'file'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Fix permissions on file /var/lib/samba/bind-dns/dns.keytab'
  file:
    path: '/var/lib/samba/bind-dns/dns.keytab'
    state: 'file'
    owner: 'root'
    group: "{{ bind_group }}"
    mode: '0640'

- name: 'Fix permissions on directory /var/lib/samba/bind-dns/dns'
  file:
    path: '/var/lib/samba/bind-dns/dns'
    state: 'directory'
    owner: 'root'
    group: "{{ bind_group }}"
    mode: '0770'

- name: 'Fix permissions on file /var/lib/samba/bind-dns/dns/sam.ldb'
  file:
    path: '/var/lib/samba/bind-dns/dns/sam.ldb'
    state: 'file'
    owner: 'root'
    group: "{{ bind_group }}"
    mode: '0660'
