---
# samba4_ad_domaincontroller/tasks/Debian10_prepare_dns.yml

- name: 'Set TRUNCATE_NAMESERVER_LIST_AFTER_LOOPBACK_ADDRESS in /etc/default/resolvconf'
  lineinfile:
    path: '/etc/default/resolvconf'
    regex: '^TRUNCATE_NAMESERVER_LIST_AFTER_LOOPBACK_ADDRESS'
    line: 'TRUNCATE_NAMESERVER_LIST_AFTER_LOOPBACK_ADDRESS="yes"'
    create: 'true'
    owner: 'root'
    group: 'root'
    mode: '0644'
