---
# samba4_ad_domaincontroller/tasks/Debian10_prepare_dns.yml

- name: 'Set TRUNCATE_NAMESERVER_LIST_AFTER_LOOPBACK_ADDRESS in /etc/default/resolvconf'
  lineinfile:
    path: '/etc/default/resolvconf'
    regex: '^TRUNCATE_NAMESERVER_LIST_AFTER_LOOPBACK_ADDRESS'
    line: 'TRUNCATE_NAMESERVER_LIST_AFTER_LOOPBACK_ADDRESS="yes"'
    create: 'true'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Add settings to /etc/bind/named.conf.options'
  template:
    src: 'Debian10/named.conf.options.j2'
    dest: '/etc/bind/named.conf.options'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Add include for /var/lib/samba/bind-dns/named.conf to /etc/bind/named.conf.local'
  lineinfile:
    path: '/etc/bind/named.conf.local'
    regex: 'include /var/lib/samba/bind-dns/named.conf'
    line: 'include /var/lib/samba/bind-dns/named.conf'
    create: 'true'
    owner: 'root'
    group: 'bind'
    mode: '0644'
