---
# samba4_ad_domaincontroller/tasks/install_packages.yml

- name: 'Install Samba4 packages'
  package:
    name: "{{ samba4_packages }}"
    state: 'present'
  notify:
    - 'Remove file smb.conf (if it was created during installation)'
    - 'Stop Samba4 AD Domaincontroller services directly after the packages were installed'
