---
# samba4_ad_domaincontroller/tasks/main.yml

- name: "Load variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"

- name: 'Install packages'
  include_tasks: install_packages.yml

- name: 'Disable services not in use on the Samba4 AD Domaincontrollers'
  include_tasks: disable_unused_services.yml

- name: 'Enable Samba4 AD Domaincontroller services'
  include_tasks: enable_samba_ad_dc_services.yml
