---
# samba4_ad_domaincontroller/handlers/main.yml

- name: 'Stop Bind service if it has been started during installation'
  service:
    name: "{{ bind_systemd_unit }}"
    state: 'stopped'
    enabled: 'true'

- name: 'Remove file smb.conf (if it was created during installation)'
  file:
    path: "{{ path_to_smb_conf }}"
    state: 'absent'
